<center><h1>Analyse des données avec Python</h1></center>

 <center><h1><font color="#660000"> Les tableaux avec la bibliothèque Numpy</font></h1></center>
 
 <hr>
<img src="Numpy_logo.png" width="240" height="240" align="center"/>

 
 <hr>

<center><i>Notebook créer par : Walid ABDELJAWED</i></center>
<hr>
 

## Introduction


Numpy, pour NUMerical PYthon est un package de base contenant des fonctions et des objets essentiels au traitement de données en Python.

Numpy est un package Python spécialisé dans la manipulation des tableaux (array) : Vecteur et Matrices

Pour utiliser la biblioyhèque Numpy, il faut importer la bibliothèque avec l'instruction suivante:


In [1]:
import numpy as np

 ## Caractéristiques

-  Les tableaux « numpy » ne gère que les objets de même type.
-  Le package propose un grand nombre de routines pour un accès rapide aux données (ex. recherche, extraction), pour les manipulations diverses (ex. tri), pour les calculs (ex. calcul statistique) 
- Les  tableaux Numpy  sont plus performants (rapidité) que les collections usuelles  de Python (Listes)

### Exemple pour expliqué la performance

Créons deux listes de longueur 1000 chacune, avec des nombres tirés aléatoirement à l’aide de la fonction random() du module random. Divisons chaque élément de la première liste par l’élément à la même position dans la seconde ligne, puis calculons la somme de ces 1000 divisions.

In [2]:
from random import random
from operator import truediv
l1 = [random() for i in range(1000)]
l2 = [random() for i in range(1000)]
%timeit s = sum(map(truediv,l1,l2))

90.1 µs ± 6.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Créons deux tableaux dont leurs contenus sont les deux listes créer précédament, et fesons le même calcul

In [3]:
a1 = np.array(l1)
a2 = np.array(l2)
%timeit s = np.sum(a1/a2)

12.8 µs ± 240 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## I. Création de Tableau
### 1. Tableau à partir d'une Liste
#### a. Création de tableau et matrice

In [4]:
import numpy as np
Vect = np.array([1,2,5,4])
print(Vect)

[1 2 5 4]


In [5]:
Mat = np.array([[2.5,3,5],[4,0,1]])
print(Mat)

[[2.5 3.  5. ]
 [4.  0.  1. ]]


#### b. Les attributs du tableau:
* type(tableau) : Type de la structure ==> ndarray
* tableau.dtype : Type des valeurs du tableau
* tableau.ndim  : Nombre de dimensions
* tableau.size  : Nombre des éléménents du tableau
* tableau.shape : Nombre de ligne et de colonne

In [6]:
# caractéristiques du tableau Vect:
print(type(Vect))
print(Vect.dtype)
print(Vect.ndim)
print(Vect.size)
print(Vect.shape)

<class 'numpy.ndarray'>
int32
1
4
(4,)


In [7]:
# caractéristiques de la matrice Mat:
print(type(Mat))
print(Mat.dtype)
print(Mat.ndim)
print(Mat.size)
print(Mat.shape)

<class 'numpy.ndarray'>
float64
2
6
(2, 3)


#### c. Typage des données
1. Typage implicite:
Créer le tableau sans déclarer le type de ces valeurs
2. Typage explicite (Préférable):
On utilise l'attribut dtype=type (avec type int, float, bool, ...) pour déclarer le type des valeurs

In [8]:
#typage implicite
a= np.array([1,2,3,4])
#typage explicite
a= np.array([1,2,3,4],dtype=float)
#Vecteur de booléen
a= np.array([True,False,True,True],dtype=bool)

### 2. Création à partir des fonctions prédéfinies
#### a. La fonction arange
Syntaxe:

<h4><center><b><i>a = np.arange(start= , stop= ,step = )</i></b></center></h4>

<b>NB:</b> les étiquettes start, stop et step ne sont pas obligatoires

In [9]:
a = np.arange(start=2,stop=10)
print(a)

[2 3 4 5 6 7 8 9]


In [10]:
a = np.arange(start=0,stop=20,step=3)
print(a)

[ 0  3  6  9 12 15 18]


#### b. La fonction linspace
Syntaxe

<h4><center><b><i>a = np.linspace(start= , stop= , num= )</i></b></center></h4>

<b>NB:</b> les étiquettes start, stop et num ne sont pas obligatoires

In [12]:
a = np.linspace(0,10,5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


#### c. la fonction ones
Syntaxe:

<h4><center><b><i>a = np.ones(shape= Nb)</i></b></center></h4>

<b>NB:</b> l'étiquette shape n'est pas obligatoire

In [13]:
a = np.ones(shape=5)
print(a)

[1. 1. 1. 1. 1.]


In [14]:
a = np.ones((2,3,4),dtype=int)
print(a)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


#### d. la fonction zeros
Syntaxe:

<h4><center><b><i>a = np.zeros(shape= Nb)</i></b></center></h4>

In [15]:
a= np.zeros(10, dtype=int)
print(a)

[0 0 0 0 0 0 0 0 0 0]


#### e. la fonction full

Syntaxe:

<h4><center><b><i>a = np.full(shape= Nb,full_value=Val)</i></b></center></h4>

In [17]:
a = np.full(5,111)
print(a)

[111 111 111 111 111]


### 3. Créer un tableau avec des valeurs aléatoires
Syntaxe:

<h4><center><b><i>random.randint(Valeur_min,Valeur_max_exclu,size)</i></b></center></h4> : valeur entre [Valeur_min,Valeur_max[ de type entier

<h4><center><b><i>random.random(size)</i></b></center></h4> : Valeur entre [0,1[ de type réel

In [18]:
np.random.seed(0)
a =np.random.randint(10,100,5)
print(a)

[54 57 74 77 77]


In [19]:
a = np.random.randint(10,size=(2,5))
print(a)

[[7 9 3 5 2]
 [4 7 6 8 8]]


In [20]:
a = np.random.random(10)
print(a)

[0.27265629 0.47766512 0.81216873 0.47997717 0.3927848  0.83607876
 0.33739616 0.64817187 0.36824154 0.95715516]


### 4. Chargement à partir d'un fichier
Syntaxe:

<h4><center><b><i>a = np.genfromtxt("nom fichier.txt",dtype=<type>,delimiter='\t')</i></b></center></h4>

In [23]:
a = np.genfromtxt("file.csv",delimiter=",",skip_header=1)
print(a)

[[1.  2.  3. ]
 [4.  5.5 6. ]]


In [25]:
a = np.genfromtxt("file.csv",delimiter=",",skip_header=1,usecols=[0,2],dtype=np.int8)
print(a)

[[1 3]
 [4 6]]


## II. Accès au éléments du tableau
<u><b>Pour les vecteurs :</b></u> accéder à un élément d'indice <b>i</b> en utilisant la syntaxe : <b>tableau[i]</b>

<u><b>Pour les matrices:</b></u> accéder à l’élément d’indice <b>i,j</b> en utilisant la syntaxe : <b>tableau[i,j]</b> ou <b>tableau[i][j]</b>


In [30]:
import numpy as np
a = np.arange(1,13)
b = np.arange(1,13).reshape(4,3)
print("Tableau a : ",a)
print("\nTableau b:\n",b)

Tableau a :  [ 1  2  3  4  5  6  7  8  9 10 11 12]

Tableau b:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### 1. Premier élément et dernier élément d'un tableau et d'une matrice

In [31]:
# Premier élément du tableau a
print(a[0])

1


In [34]:
# Premier élément du tableau b : 1ière méthode
print(b[0,0])

1


In [35]:
# Premier élément du tableau b : 2ième méthode 
print(b[0][0])

1


In [36]:
# Dernier élément du tableau a: 1ière méthode
print(a[a.size-1])

12


In [37]:
# Dernier élément du tableau a : 2ième méthode
print(a[-1])

12


In [39]:
# Dernier élément du tableau b : 1ière méthode
print(b[b.shape[0]-1,b.shape[1]-1])

12


In [40]:
# Dernier élément du tableau b : 2ième méthode
print(b[-1,-1])

12


### 2. Extraction d’une suite éléments du tableau : Slicing
L’accès aux éléments d’un tableau se fait de la même manière que pour les listes, grâce à l’indiçage. La syntaxe est la suivante : <b>tableau[lower:upper:step]</b>

avec <b><i>lower</i></b> la borne inférieur de la plage d’indices, <b><i>upper</i></b> la plage supérieur, et <b><i>step</i></b> l’espacement entre les valeurs.

* Lorsque <i><b>lower</b></i> n’est pas précisé, le premier élément (indicé 0) est considéré comme la valeur attribuée à lower.
* Lorsque <i><b>upper</b></i> n’est pas précisé, le dernier élément est considéré comme la valeur attribuée à upper.
* Lorsque <i><b>step</b></i> n’est pas précisé, un pas de 1 est attribué par défaut.



#### a. Tableau à une dimension

In [41]:
a = np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [42]:
# Extraire du 4ième élément au 6ième élément
a[3:6] # utiliser une variable pour la sauvgarder ou utiliser print pour afficher

array([4, 5, 6])

In [46]:
# Extraire du 4ième élément jusqu'a la fin
print(a[3:])

[ 4  5  6  7  8  9 10 11 12]


In [44]:
# Extraire du premier élément jusqu'à le 3ième élément
print(a[:3])

[1 2 3]


#### b. Tableau à deux dimensions

In [52]:
b = np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
# Première colonne
print(b[:,0])

[1 5 9]


In [54]:
# Première et 3ième colonne
print(b[:,[0,2]])

[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [55]:
# Du deuxième au dernière colonne
print(b[:,1:])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


#### c. Extraction à l'aide des booléen

In [58]:
masque_bool = [False,True]*6
masque = np.array(masque_bool)
masque

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True])

In [59]:
a = np.arange(1,13,dtype=np.int8)
print(a[masque])

[ 2  4  6  8 10 12]


In [60]:
# Afficher les éléments pairs du tableau a
print(a[a%2==0])

[ 2  4  6  8 10 12]


In [62]:
# Afficher les valeurs >=10
c = np.random.randint(0,20,10)
print(c[c>=10])

[10 11 18]


## III. Modification des valeurs du tableau

In [64]:
a = np.arange(1,13).reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
a[0]=[11,12,13]
a

array([[11, 12, 13],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [67]:
a[0,1:]=2
a

array([[11,  2,  2],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### 1. Ajouter une valeur à la fin du tableau

Pour ajouter une valeur à la fin d’un tableau, on utilise la fonction <i><b>append<b></i>


In [2]:
import numpy as np
a = np.random.randint(1,11,5)
a

array([7, 6, 4, 9, 7])

In [5]:
# Ajouter la valeur 20 à la fin du tableau
np.append(a,20)

array([ 7,  6,  4,  9,  7, 20])

In [4]:
# Le tableau n'est pas changer
a

array([7, 6, 4, 9, 7])

In [6]:
# La solution: Sauvegarder le résultat de append dans une variable
a = np.append(a,20)
a

array([ 7,  6,  4,  9,  7, 20])

### 2. Insérer une valeur dans un tableau
Pour insérer une valeur dans un tableau on utilise la fonction <b><i>insert</i></b> avec la syntaxe suivante:
   <center> <h5><b><i>insert(Nom_tab,position,valeur)</i></b></h5></center>

In [38]:
# insérer la valeur 50 dans la position 2 du tableau
a = np.insert(a,2,50)
a

array([ 7,  6, 50,  4,  9,  7, 20])

### 3. Ajouter une ligne à une matrice

In [30]:
## Création de la matrice
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
# Création d'une ligne
ligne = np.array([[7,8,9]])
ligne

array([[7, 8, 9]])

In [32]:
# Ajout de la ligne à la fin de la matrice
b = np.append(b,ligne, axis =0)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 3. Insérer une ligne dans une matrice

Pour insérer une ligne ou une colonne dans une matrice on utilise la fonction <b><i>insert</i></b>, avec la syntaxe suivante:
    <center><b><i><h5>insert(Nom_matrice,position,valeur,axis)</h5></i></B></center>
    avec axis = 0 pour insérer une ligne et 1 pour insérer une colonne

In [33]:
b = np.insert(b,1,[[0,0,0]],axis=0)
b

array([[1, 2, 3],
       [0, 0, 0],
       [4, 5, 6],
       [7, 8, 9]])

### 4. Ajouter une colonne à la fin d'une matrice

In [34]:
# Création d'une colonne
colonne =np.array([[9],[9],[9],[9]])
colonne

array([[9],
       [9],
       [9],
       [9]])

In [35]:
b = np.append(b,colonne,axis=1)
b

array([[1, 2, 3, 9],
       [0, 0, 0, 9],
       [4, 5, 6, 9],
       [7, 8, 9, 9]])

### 5. Insérer une colonne dans une matrice

In [36]:
# Création d'une colonne
colonne = np.array([8,8,8,8]).reshape(4,1)
b= np.insert(b,[0],colonne,axis=1)
b

array([[8, 1, 2, 3, 9],
       [8, 0, 0, 0, 9],
       [8, 4, 5, 6, 9],
       [8, 7, 8, 9, 9]])

#### Remarque:

il faut mêtre la position d'insertion entre deux crochets

## IV. Copie de tableau 

In [42]:
a = np.array([1,2,3,4])
b = a
b[0] = 1000
print("tableau a:",a)
print("tableau b:",b)

tableau a: [1000    2    3    4]
tableau b: [1000    2    3    4]


#### Remarque :
Lorsqu'on fait une copie du tableau avec le signe <b>=</b> toute modification se fait sur la copie à un impact sur le tableau d'origine

In [43]:
a = np.array([1,2,3,4])
b= np.copy(a)
b[0]=1000
print("tableau a:",a)
print("tableau b:",b)

tableau a: [1 2 3 4]
tableau b: [1000    2    3    4]


#### Remarque : 
Pour faire une copie d'un tableau, il faut utiliser la fonction <b>copie</b>

## V.Tri du tableau

<h5><b><i><center>sort(nom_tableau,axis={-1,0,1},kind={"quicksort", "mergesort", "heapsort", "stable"})</center></i></b></h5>
avec 

* axis = -1 : suivant le dernier axe)
* axis = 0 : tri par colonne) 
* axis= 1 : tri par ligne)
* rien : le tableau sera aplati avnt le tri

In [44]:
# Création du tableau
a = np.random.randint(10,100,10)
a

array([55, 94, 50, 58, 44, 35, 85, 33, 52, 92])

In [45]:
# l'ordre des index qui permettrait le tri
print(np.argsort(a))

[7 5 4 2 8 0 3 6 9 1]


In [46]:
# Tri
a = np.sort(a)
# Affichage du tableau apès Tri
print(a)

[33 35 44 50 52 55 58 85 92 94]


In [49]:
b = np.random.randint(10,99,16).reshape(4,4)
b

array([[35, 56, 49, 83],
       [60, 81, 27, 98],
       [61, 66, 97, 24],
       [33, 18, 96, 28]])

In [50]:
# Tri par colonne, méthode mergesort
c =np.sort(b,0,"mergesort")
c

array([[33, 18, 27, 24],
       [35, 56, 49, 28],
       [60, 66, 96, 83],
       [61, 81, 97, 98]])

In [51]:
# tri par ligne, méthode heapsort
t = np.sort(b,1,"heapsort")
t

array([[35, 49, 56, 83],
       [27, 60, 81, 98],
       [24, 61, 66, 97],
       [18, 28, 33, 96]])

## VI. Les fonctions universelles

Une fonction universelle (le terme exact est « ufunc », abréviation de universal function) est une fonction qui peut s’appliquer terme à terme aux éléments d’un tableau.

### 1. Calcul arithmétique

In [53]:
a = np.arange(1,10,dtype=int)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
a *10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
1/a

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [57]:
a**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

### 2. Calcul arithmétique sur les tableaux

* <b>add(a,b)</b> additionne terme à terme les éléments de a et b (autre syntaxe possible : a + b)
* <b>subtract(a,b)</b> soustrait terme à terme les éléments de b à ceuxdea (autre syntaxe possible : a - b )
* <b>multiply(a,b)</b> multiplie terme à terme les éléments de a et b (autre syntaxe possible : a ∗ b)
* <b>divide(a,b)</b> quotients (flottants) terme à terme des éléments de a par ceux de b (autre syntaxe : a/b)
* <b>floor_divide(a,b)</b> quotients (entiers) des divisions des éléments de a par ceux de b (autre syntaxe : a//b)
* <b>power(a,b)</b> élève les éléments de a à la puissance les éléments de b
* <b>mod(a,b)</b> donne les restes dans les divisions des éléments de a par ceux de b
* <b>negative(a)</b> (tableaux des opposés : autre syntaxe possible -a),
* <b>absolute(a)</b> (modules), 
* <b>sign(a)</b>  Signes des éléments de x (0, 1 ou -1)
* <b>rint(a)</b> (à l’entier), 
* <b>floor(a)</b>  Troncature de x à l’entier inférieur
* <b>ceil(a)</b> Troncature de x à l’entier supérieur 
* <b>trunc(a)</b> troncature, 
* <b>round_(a,n)</b> arrondi les éléments du tableau a à n décimales
* <b>sqrt</b>  Racine carré
* <b>square</b>: Carré
* <b>sin cos tan arcsin arccos arctan sinh cosh tanh arcsinh arccosh arctanh</b>
* ...
 
Télécharger le document pdf à partir de ce <a href="http://perso.univ-perp.fr/langlois/images/pdf/mp/www.mathprepa.fr-une-petite-reference-numpy.pdf">lien </a>pour les autres fonctions avec des exemples. 


## VII. Les fonctions statistiques

<img src="img/MMS.png"/>

In [58]:
a = np.random.randint(0,100,10)
a

array([ 4, 34, 85, 58, 41,  6, 17, 58,  7, 31])

In [60]:
# Calcul de sommes des éléments
print("somme = ",np.sum(a))
# Cacul du produit
print("Produit = ",np.prod(a))
# recherche du maximum et sa position
print("le max est ",np.max(a),"à la position",np.argmax(a))
# Calcul de la somme cumulé à la position 5
print("la somme cumulé est égale à",np.cumsum(a))

somme =  341
Produit =  -1264798272
le max est  85 à la position 2
la somme cumulé est égale à [  4  38 123 181 222 228 245 303 310 341]


## VIII. Les fonctions logiques

<img src="img/logique.png"/>

In [61]:
a = np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
print(np.greater(a,5))

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [63]:
print(a>5)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [64]:
t = np.array([[1,10,3,24],[9,12,40,2],[0,7,2,14]])
masque = np.logical_and(t<=20,t>=10)
print("masque:\n",masque)
print("les éléments de t compris entre 10 et 20:\n",t[masque])

masque:
 [[False  True False False]
 [False  True False False]
 [False False False  True]]
les éléments de t compris entre 10 et 20:
 [10 12 14]


## IX. Produit matriciel

In [66]:
A = np.arange(0,9).reshape(3,3)
print(A,"\n")
B = np.ones((3,3))
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [67]:
C = np.dot(A,B)
print(C)

[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [68]:
D = A @ B
D

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

## X. Les constantes de Numpy
<img src="img/const.png"/>

## XI. Manipulations des tableaux
### 1. Joindre des tableaux
#### a. Joindre des tableaux horizontalement

In [74]:
A = np.ones((3,3))
B = np.zeros((3,3))
C = np.hstack((A,B))
print(C)

[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


#### b. Joindre des tableaux verticalement

In [75]:
C = np.vstack((A,B))
print(C)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### c. rows_stack et column_stack

In [82]:
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])
A = np.column_stack((a, b, c))
A

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [83]:
B = np.row_stack((a, b, c))
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 2. Diviser en tableaux
#### a. Dévision horizontale

In [76]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [79]:
[B,C] = np.hsplit(A,2)
B

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [78]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

#### b.Division verticale

In [80]:
A = np.arange(16).reshape((4, 4))
[B,C] = np.vsplit(A,2)
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [81]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])